# Configuração do Banco de Dados Principal (Master)
spring.datasource.url=jdbc:postgresql://localhost:5432/master
spring.datasource.username=postgres
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuração do Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Configuração do Multi-Tenancy (Database Per Tenant)
multitenancy.datasource.url-template=jdbc:postgresql://localhost:5432/%s
multitenancy.datasource.username=postgres
multitenancy.datasource.password=admin

spring.web.cors.allowed-origins=*
spring.web.cors.allowed-methods=*
spring.web.cors.allowed-headers=*